resources:
- name: installation
  type: s3
  source:
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-key))
    bucket: ((platform-automation-bucket))
    regexp: backups/installation/installation-(.*).zip

- name: midnight
  type: time
  source:
    start: 5:06 AM
    stop: 5:09 AM

# - name: state
#   type: s3
#   source:
#     access_key_id: ((s3-access-key-id))
#     secret_access_key: ((s3-secret-key))
#     bucket: ((platform-automation-bucket))
#     versioned_file: state.yml
#     initial_content_text: '{}'
#     initial_version: 'empty-start'

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-key))
    bucket: ((platform-automation-bucket))
    versioned_file: vsphere-platform-automation-image-5.3.0.tar.gz

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-key))
    bucket: ((platform-automation-bucket))
    regexp: .*tasks-(.*).zip
    
- name: configuration
  type: git
  source:
    uri: https://github.com/drewilgenfritz-alt/concourse.git
    branch: main
  
prepare-tasks-with-secrets: &prepare-tasks-with-secrets
  image: platform-automation-image
  file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
  input_mapping:
    tasks: platform-automation-tasks
    config: configuration
    vars: configuration
  params:
    CONFIG_PATHS: config/config
    VARS_PATHS: vars/vars
  output_mapping:
    tasks: platform-automation-tasks


jobs:
  - name: test-platform-automation
    serial: true
    plan:
      - in_parallel:
        - get: platform-automation-image
          params:
            unpack: true
        - get: platform-automation-tasks
          params:
            unpack: true
        - get: configuration
      - task: test-interpolate
        image: platform-automation-image
        file: platform-automation-tasks/tasks/test-interpolate.yml
        params:
          CONFIG_FILE: config/vars/env.yml
          SKIP_MISSING: true
        input_mapping:
          config: configuration
      - task: test
        file: platform-automation-tasks/tasks/test.yml
        image: platform-automation-image
  - name: export-installation
    serial: true
    plan:
      - get: platform-automation-image
        params:
          unpack: true
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: configuration
      - get: midnight
        trigger: true
      - task: prepare-tasks-with-secrets
        <<: *prepare-tasks-with-secrets
      - task: export-installation
        image: platform-automation-image
        file: platform-automation-tasks/tasks/export-installation.yml
        input_mapping:
          env: configuration
        params:
          ENV_FILE: config/vars/env.yml
      - put: installation
        params: { file: installation/installation-*.zip }
