resource_types:
- name: time
  type: registry-image
  source:
    repository: concourse/time-resource

resources:
- name: rotation-timer
  type: time
  source:
    interval: 24h

- name: concourse-repo
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))

jobs:
- name: rotate-uaa-credentials
  plan:
  - get: rotation-timer
    trigger: true
  - get: concourse-repo
  - task: rotate-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      inputs:
      - name: concourse-repo
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.admin-client-id))
        CLIENT_SECRET: ((uaa.admin-client-secret))
        TARGET_CLIENT: ((uaa.target-client-id))
        CREDHUB_URL: ((credhub.url))
        CREDHUB_CLIENT: ((credhub.client-id))
        CREDHUB_SECRET: ((credhub.client-secret))
        CREDHUB_PATH: ((credhub.path))
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          apt-get update && apt-get install -y curl jq openssl
          chmod +x concourse-repo/scripts/rotate-uaa-credentials.sh
          ./concourse-repo/scripts/rotate-uaa-credentials.sh

- name: verify-rotation
  plan:
  - get: rotation-timer
    trigger: true
    passed: [rotate-uaa-credentials]
  - task: verify-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.target-client-id))
        CLIENT_SECRET: ((rotated-uaa-secret))
      run:
        path: bash
        args:
        - -c
        - |
          apt-get update && apt-get install -y curl jq
          
          echo "Verifying rotated credentials..."
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST "$UAA_URL/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -d "grant_type=client_credentials")
          
          http_code=$(echo "$response" | grep -o 'HTTPSTATUS:[0-9]*' | cut -d: -f2)
          response=$(echo "$response" | sed 's/HTTPSTATUS:[0-9]*$//')
          
          if [ "$http_code" = "200" ]; then
            token=$(echo "$response" | jq -r '.access_token')
            if [ "$token" != "null" ] && [ -n "$token" ]; then
              echo "✅ Verification successful - rotated credentials work"
            else
              echo "❌ Verification failed - invalid token"
              exit 1
            fi
          else
            echo "❌ Verification failed - HTTP $http_code"
            exit 1
          fi