resource_types:
- name: time
  type: registry-image
  source:
    repository: concourse/time-resource

resources:
- name: rotation-timer
  type: time
  source:
    interval: 1h

- name: repo
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))
    paths: [scripts/rotate-uaa-credentials.sh]

jobs:
- name: rotate-uaa-credentials
  serial: true
  plan:
  - get: rotation-timer
    trigger: true
  - get: repo
  - task: rotate-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      inputs:
      - name: repo
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.admin-client-id))
        CLIENT_SECRET: ((uaa.admin-client-secret))
        TARGET_CLIENT: ((uaa.target-client-id))
        CREDHUB_URL: ((credhub.url))
        CREDHUB_CLIENT: ((credhub.client-id))
        CREDHUB_SECRET: ((credhub.client-secret))
        CREDHUB_PATH: ((credhub.path))
      run:
        path: bash
        args:
        - -c
        - |
          set -euo pipefail
          apt-get update -qq && apt-get install -y -qq curl jq openssl
          chmod +x repo/scripts/rotate-uaa-credentials.sh
          cd repo
          ./scripts/rotate-uaa-credentials.sh

- name: verify-rotation
  serial: true
  plan:
  - get: rotation-timer
    trigger: true
    passed: [rotate-uaa-credentials]
  - task: verify-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.target-client-id))
        CLIENT_SECRET: ((rotated-uaa-secret))
      run:
        path: bash
        args:
        - -c
        - |
          set -euo pipefail
          apt-get update -qq && apt-get install -y -qq curl jq
          
          echo "Verifying rotated credentials..."
          TOKEN=$(curl -s -X POST "$UAA_URL/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -d "grant_type=client_credentials" | jq -r '.access_token')
          
          if [[ "$TOKEN" != "null" && -n "$TOKEN" ]]; then
            echo "✅ Verification successful - rotated credentials work"
          else
            echo "❌ Verification failed - rotated credentials don't work"
            exit 1
          fi