resource_types:
- name: time
  type: registry-image
  source:
    repository: concourse/time-resource

resources:
- name: rotation-timer
  type: time
  source:
    interval: 24h  # Rotate daily

- name: concourse-repo
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))

jobs:
- name: rotate-uaa-credentials
  plan:
  - get: rotation-timer
    trigger: true
  - get: concourse-repo
  - task: rotate-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      inputs:
      - name: concourse-repo
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.admin-client-id))
        CLIENT_SECRET: ((uaa.admin-client-secret))
        TARGET_CLIENT: ((uaa.target-client-id))
        CREDHUB_URL: ((credhub.url))
        CREDHUB_CLIENT: ((credhub.client-id))
        CREDHUB_SECRET: ((credhub.client-secret))
        CREDHUB_PATH: ((credhub.path))
        SKIP_TLS_VERIFY: "false"  # Set to "true" if using self-signed certs
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          apt-get update && apt-get install -y curl jq openssl
          chmod +x concourse-repo/scripts/rotate-uaa-credentials.sh
          ./concourse-repo/scripts/rotate-uaa-credentials.sh
    on_failure:
      task: log-failure
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: ubuntu
            tag: 20.04
        run:
          path: echo
          args: ["UAA credential rotation failed - check logs above"]

- name: verify-rotation
  plan:
  - get: rotation-timer
    trigger: true
    passed: [rotate-uaa-credentials]
  - task: test-new-credentials
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 20.04
      params:
        UAA_URL: ((uaa.url))
        CLIENT_ID: ((uaa.target-client-id))
        CLIENT_SECRET: ((rotated-uaa-secret))
      run:
        path: bash
        args:
        - -c
        - |
          apt-get update && apt-get install -y curl jq
          echo "Verifying rotated credentials work..."
          
          TOKEN=$(curl -k -s -X POST "$UAA_URL/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -d "grant_type=client_credentials" | jq -r '.access_token' 2>/dev/null || echo "")
          
          if [ -n "$TOKEN" ] && [ "$TOKEN" != "null" ]; then
            echo "✅ Rotated credentials verification successful"
          else
            echo "❌ Rotated credentials verification failed"
            exit 1
          fi